sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '0.12'
  - '4.2.2'
  - '6'
before_script:
  - npm prune
script:
  - ./next-update-travis.sh
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
